// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UNI_EDU_Backend.Infrastructure;

#nullable disable

namespace UNI_EDU_Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260702054615_AddClassRequestDurationMonths")]
    partial class AddClassRequestDurationMonths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.AiTestAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("AiTestAttempts");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WithName")
                        .HasColumnType("text");

                    b.Property<Guid?>("WithUserId")
                        .HasColumnType("uuid");

                    b.HasKey("AppointmentID");

                    b.HasIndex("WithUserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuditLogID");

                    b.HasIndex("ActorUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SenderID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageID");

                    b.HasIndex("SenderID");

                    b.HasIndex("ClassID", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Class", b =>
                {
                    b.Property<Guid>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompletedSessions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EscrowAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EscrowReleased")
                        .HasColumnType("numeric");

                    b.Property<int>("EscrowStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseMilestone")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<decimal>("TuitionFee")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TutorID")
                        .HasColumnType("uuid");

                    b.Property<string>("WeeklySlots")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("ClassID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TutorID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ClassChatRead", b =>
                {
                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClassID", "UserID");

                    b.ToTable("ClassChatReads");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ClassMaterial", b =>
                {
                    b.Property<Guid>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MaterialID");

                    b.HasIndex("ClassID");

                    b.ToTable("ClassMaterials");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ClassRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AcceptedSubmissionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedTutorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Budget")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PreferredSchedule")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassRequests");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.DmMessage", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TutorID")
                        .HasColumnType("uuid");

                    b.HasKey("MessageID");

                    b.HasIndex("TutorID", "ParentID", "SentAt");

                    b.ToTable("DmMessages");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.EmailOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Consumed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EmailOtps");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Exam", b =>
                {
                    b.Property<int>("ExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExamID"));

                    b.Property<bool>("AiProctoring")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CreatorTutorID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxAttemptsPerUser")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreScale")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ExamID");

                    b.HasIndex("CreatorTutorID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ExamAiConfig", b =>
                {
                    b.Property<Guid>("ConfigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoGenerateEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("CopyPasteBlocked")
                        .HasColumnType("boolean");

                    b.Property<string>("DefaultDifficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FaceDetection")
                        .HasColumnType("boolean");

                    b.Property<bool>("FullscreenRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProctoringEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("TabSwitchLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConfigID");

                    b.ToTable("ExamAiConfigs");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ExamQuestion", b =>
                {
                    b.Property<int>("ExamID")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionID")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("integer");

                    b.HasKey("ExamID", "QuestionID");

                    b.HasIndex("QuestionID");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Incident", b =>
                {
                    b.Property<Guid>("IncidentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ReporterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReporterRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("IncidentID");

                    b.HasIndex("ClassID");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("SessionID");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.LearningStreak", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastActivityDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserID");

                    b.ToTable("LearningStreaks");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Message", b =>
                {
                    b.Property<Guid>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SenderID")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageID");

                    b.HasIndex("ClassID");

                    b.HasIndex("SenderID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Parent", b =>
                {
                    b.Property<Guid>("ParentID")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ParentID");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ParentChildLinkRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParentID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.HasIndex("StudentID");

                    b.ToTable("ParentChildLinkRequests");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Standard")
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uuid");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("QuestionID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("TokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.RefundRequest", b =>
                {
                    b.Property<Guid>("RefundRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RequesterUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RefundRequestID");

                    b.HasIndex("ClassID");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("ReviewerID");

                    b.ToTable("RefundRequests");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewID"));

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReviewerID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorID")
                        .HasColumnType("uuid");

                    b.HasKey("ReviewID");

                    b.HasIndex("ClassID");

                    b.HasIndex("ReviewerID");

                    b.HasIndex("TutorID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Room", b =>
                {
                    b.Property<Guid>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Building")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Session", b =>
                {
                    b.Property<Guid>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool?>("AbsenceApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("AbsenceReason")
                        .HasColumnType("text");

                    b.Property<string>("AbsenceRequestedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("ClassID")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("Homework")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("HomeworkFiles")
                        .HasColumnType("text[]");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("OfficeConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("RatingComment")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SessionID");

                    b.HasIndex("ClassID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Student", b =>
                {
                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableSlots")
                        .HasColumnType("jsonb");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uuid");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StudentID");

                    b.HasIndex("ParentID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Subject", b =>
                {
                    b.Property<Guid>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubjectID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Submission", b =>
                {
                    b.Property<int>("SubmissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionID"));

                    b.Property<string>("AIFeedback")
                        .HasColumnType("text");

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExamID")
                        .HasColumnType("integer");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("SubmissionID");

                    b.HasIndex("ExamID");

                    b.HasIndex("UserID");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.SystemSetting", b =>
                {
                    b.Property<Guid>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableChat")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableExams")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnablePayments")
                        .HasColumnType("boolean");

                    b.Property<int>("EscrowHoldDays")
                        .HasColumnType("integer");

                    b.Property<int>("EscrowPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionTimeout")
                        .HasColumnType("integer");

                    b.Property<bool>("SmsNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("TwoFactorAuth")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SettingID");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TrialBooking", b =>
                {
                    b.Property<Guid>("TrialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentLevel")
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<string>("Goals")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentID")
                        .HasColumnType("uuid");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorID")
                        .HasColumnType("uuid");

                    b.HasKey("TrialID");

                    b.HasIndex("ParentID");

                    b.HasIndex("StudentID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("TutorID");

                    b.ToTable("TrialBookings");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Tutor", b =>
                {
                    b.Property<Guid>("TutorID")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Achievements")
                        .HasColumnType("text[]");

                    b.Property<string>("AvailableSlots")
                        .HasColumnType("jsonb");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<float?>("AverageRating")
                        .HasColumnType("real");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankAccountHolder")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Certificates")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("HourlyRate")
                        .HasColumnType("integer");

                    b.Property<string>("IntroVideoUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("School")
                        .HasColumnType("text");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("text");

                    b.Property<string>("TeachingStyle")
                        .HasColumnType("text");

                    b.Property<int?>("TutorType")
                        .HasColumnType("integer");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer");

                    b.HasKey("TutorID");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TutorPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradeLevels")
                        .HasColumnType("text");

                    b.Property<int?>("HourlyRate")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PreferredSchedule")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("TutorPosts");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TutorPostApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TutorPostId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorPostId");

                    b.ToTable("TutorPostApplications");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TutorSubject", b =>
                {
                    b.Property<Guid>("TutorID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubjectID")
                        .HasColumnType("uuid");

                    b.HasKey("TutorID", "SubjectID");

                    b.HasIndex("SubjectID");

                    b.ToTable("TutorSubjects");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Wallet", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EscrowBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserID");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.WalletTransaction", b =>
                {
                    b.Property<Guid>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTxnId")
                        .HasColumnType("text");

                    b.Property<Guid?>("RelatedClassID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionID");

                    b.HasIndex("RelatedClassID");

                    b.HasIndex("UserID");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Withdrawal", b =>
                {
                    b.Property<Guid>("WithdrawalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewerID")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TutorID")
                        .HasColumnType("uuid");

                    b.HasKey("WithdrawalID");

                    b.HasIndex("ReviewerID");

                    b.HasIndex("TutorID");

                    b.ToTable("Withdrawals");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.AiTestAttempt", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Appointment", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "WithUser")
                        .WithMany()
                        .HasForeignKey("WithUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WithUser");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.AuditLog", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ChatMessage", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Class", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Student", "Student")
                        .WithMany("Classes")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Tutor", "Tutor")
                        .WithMany("Classes")
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ClassMaterial", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany("Materials")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ClassRequest", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Exam", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Tutor", "CreatorTutor")
                        .WithMany()
                        .HasForeignKey("CreatorTutorID");

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorTutor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ExamQuestion", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Incident", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("Reporter");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.LearningStreak", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("UNI_EDU_Backend.Domain.Models.LearningStreak", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Message", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Notification", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Parent", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("UNI_EDU_Backend.Domain.Models.Parent", "ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.ParentChildLinkRequest", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Question", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.RefreshToken", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.RefundRequest", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("Requester");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Review", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany("Reviews")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Reviewer");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Session", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Student", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("UNI_EDU_Backend.Domain.Models.Student", "StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Submission", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Exam", "Exam")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TrialBooking", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Parent", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Tutor", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("UNI_EDU_Backend.Domain.Models.Tutor", "TutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TutorPost", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TutorPostApplication", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.TutorPost", "TutorPost")
                        .WithMany()
                        .HasForeignKey("TutorPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TutorPost");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.TutorSubject", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Tutor", "Tutor")
                        .WithMany("TutorSubjects")
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Wallet", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("UNI_EDU_Backend.Domain.Models.Wallet", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.WalletTransaction", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("RelatedClassID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Withdrawal", b =>
                {
                    b.HasOne("UNI_EDU_Backend.Domain.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UNI_EDU_Backend.Domain.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Class", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("Reviews");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Exam", b =>
                {
                    b.Navigation("ExamQuestions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Parent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Question", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Student", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Subject", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Exams");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Tutor", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("TutorSubjects");
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.User", b =>
                {
                    b.Navigation("Parent")
                        .IsRequired();

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("Submissions");

                    b.Navigation("Tutor")
                        .IsRequired();
                });

            modelBuilder.Entity("UNI_EDU_Backend.Domain.Models.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
